# Use the official MongoDB image
FROM mongo:latest

# Expose MongoDB default port
EXPOSE 27017

# (Optional) Specify a volume for persistent data:
# VOLUME ["/data/db"]

# Start MongoDB when the container launches
CMD ["mongod"]
